### ISSUE TITLE
Move the repository to the mozilla account

### ISSUE THREAD

**Issue by whimboo** [jonallengriffin/pulsebuildmonitor#2]
We should move this repository to the Mozilla account. It's helpful and other teams most likely also want to use it but are not aware of it? @jonallengriffin, mind doing that?

**Comment by jonallengriffin** [comment]
It's already done - https://github.com/mozilla/pulsetranslator

This repo is obsolete; I'll delete it.

**Comment by jonallengriffin** [comment]
Whoops, wrong repo above.  The canonical repo for pulsebuildmonitor is http://hg.mozilla.org/automation/pulsebuildmonitor

**Comment by whimboo** [comment]
Hm, ok. So yeah, please delete this repository then.
